environment:
 script:
 - echo "instruksi untuk install module yang dibutuhkan"
 - echo "instruksi untuk set-up environment variable"

test:
 script:
 - python3 manage.py test bdd
 - echo "instruksi untuk test UI"
 only:
 - master

deploy:
 script:
 - echo "instruksi untuk migrasi data"
 - echo "instruksi untuk menjalankan aplikasi/services"
 only:
 - master	
